language: node_js
node_js:
- '6'
- '8'
- '10'
if: tag IS present
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_script:
  npm i
script: npm run build
deploy:
  provider: npm
  email: github@nucleode.com
  api_key:
    secure: TUHJSGKgvqw4hmqzFhw+llyWQF6rqxZCRmaMujLLc9qNWWFfYdgtAHjxACAuhURajvMiggOswvtnTISMCFoNhMeTqIUnE+FiVj3LxA+XpRCrLVvdPP2LCe2B5NF7Yq2fznJLDp/v23H6xLzVaEbAH7aZ6VCDiiZQ5kP9P7+pIA3j+BJjxQilR6eUIWD/4wdb+zfULM1s7MfVyOChcSrC/Q2mCufQp1mvS+pWqHem0JjrNL8Pfo8US0eg37xEJNy9TAZefYt6qdz1kS3hZ3Rzjak5jLPWQEPTg4zceszbUpOlDjtAIBQUnttNZsnE8fbA5MiQviWi4ucmRVP4iFJLZhYJ4LCa48Lr2c4W231XG7HHkDDcYRHf0NjCGi0Aqv81WXGGNOQCpUmLja+xyBJbVQ74xMryE9yo8xe0Sc8/39VRvGmpNYuC5+QqSDfTRGQDyu9axtPo9x4hFiY8cUkfQDzWSRgSdSsCRxFzgbWzMfChy0BRK6RVW6AGF8leDN6FhMLc30m8bdWNIMl3S4nkrDffH4B/gM32gJS4E03C35ZqwczW5UndiPBXRI4clER2vwzAKhD+MOGR/eN6BA9A9kSP9dtx5piUxRK5p2WS7WaHN3b0Ww1MtPcy8OF2VeJGJp3YzX/f6Ead6Wy7qo7x4NGc/IYuZHcW2ssm+Vy2jKk=
  on:
    tags: true
    repo: nucleode/arecibo
notifications:
  slack:
    secure: EpGXCiUH0XI7FNCxS1/HEIHILHtqMZnlGY15vpPtXQADTdLIRp2oRiSh7mgw2NvMn/RdtSbl2X0actLppr6xBXOFueppJzlhEoxRpbjLwTWHqFTQt82ud919yu2TLsqrhqiwgKyNLKWABuhPPUQ5TTI8zg2LMWeQ/fpUGSkEswi5WXGgfO02L8vNSCFz5hFfc9yz5zYf+7MtmiZJqSBPbSEptHNF/fRq+6pOlf3v0mJtaaUkhwgqnwztJC3Mq4Ew1JRTSTaqrsnriynnHD/YjX+3kPjr8zvOkyKeHJ/XxyjMaFsHU5AnsRAcURwGw1CPZe/WIXyd11y5tlaSziwfH8wRWmXXHJLgyRdaFc1x2spZnxsKesPrgfCMe3+WDenJhoGvA/t2FHx5S+G5V2IoNNQ2JNZA0DRJU54+L8/+F7Oe3oCxhi4eJbRtp3nKNlXZ08YpM6QOL0Sv3/JizBoOpooTm9kSb3ptr6cSxtw/WJEa7pyhQG4q+esgc67OHi4fjAZCu8lfxmIafiKdckvYOTXEzyyFOxMdfnsRZdUkXHP+Dh6Jb/xejg3tQVUXNvjyxOJmNLfU6zOXST7IvYOG/8KPNqqT1JQg6W3qhoYlA99t6+HFjhPXcwRBmFLTQV6WfmTMdeQz1P0G8J+Tp+31kUZlkZkUmmkJZJ7GFT9pVgY=
