language: node_js
node_js:
- '6'
- '8'
- '10'
if: tag IS present
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
deploy:
  provider: npm
  email: kapa89@me.com
  api_key:
    secure: fZq17uunAEXB1xjb4ZTSy1E8wCMHtNfzCvZyZx5I3UzY1viOwynZHYbsgDI/4HAPDhmn1NPR8eC0uyXseogJbw7sg+4vKHEWoXGjG8Xo7kroSINz7wRS8LntoSMWmb8wmrjPN/kw3Nuoec5In03wFyFxq0DnV9tRYAdzWlWizyJB3hKPbC0mJAM/Ra9T5jOAsZEdAyp3eUrKljJLSyIhTj2xIPmxqc/ww6RDJd8AuacYDIeKSY5Uc7yA2Qy8VJ4lQUa8k6I7OpcKalDjlds1wYYX1IdGmKFD4qWFfzKGSh4EtpftCnbp5eB6hWCN5KKOdw+gBhvbegyj7xqMkBc/ud4Wuz2vC1kWCAQlmZ7nbVGcVBCpR4gyzEE1R7RMbTswmUxrAgKrSns8ojHDy/07j2dtkI50+74tr1/cXuULG0BGeuGoNgkVX33kcsHjj+DcVt19cJ4FPKSBTt3r0PSqinwJ9PRQaLiGEyEZ0Yec6Bzwzw9xWbZRIHw7jqqBBRC4gpj5Wl3Gq4H6u7sXEWfyPJl6SC8i8atgnuse94yAUcYVaeMGDIb1PGL8LCCzva5fhnlngklcibHveRPV/z3Di0Rq51fFOfKtp0SwTmgM4TkjUQ83sn61Xhd416C46QrTtdU61MzjQp8I0glpb83+AGYVK2AgkKFCTwtkk5hnNXk=
  on:
    tags: true
    repo: nucleode/arecibo
notifications:
  slack:
    secure: EpGXCiUH0XI7FNCxS1/HEIHILHtqMZnlGY15vpPtXQADTdLIRp2oRiSh7mgw2NvMn/RdtSbl2X0actLppr6xBXOFueppJzlhEoxRpbjLwTWHqFTQt82ud919yu2TLsqrhqiwgKyNLKWABuhPPUQ5TTI8zg2LMWeQ/fpUGSkEswi5WXGgfO02L8vNSCFz5hFfc9yz5zYf+7MtmiZJqSBPbSEptHNF/fRq+6pOlf3v0mJtaaUkhwgqnwztJC3Mq4Ew1JRTSTaqrsnriynnHD/YjX+3kPjr8zvOkyKeHJ/XxyjMaFsHU5AnsRAcURwGw1CPZe/WIXyd11y5tlaSziwfH8wRWmXXHJLgyRdaFc1x2spZnxsKesPrgfCMe3+WDenJhoGvA/t2FHx5S+G5V2IoNNQ2JNZA0DRJU54+L8/+F7Oe3oCxhi4eJbRtp3nKNlXZ08YpM6QOL0Sv3/JizBoOpooTm9kSb3ptr6cSxtw/WJEa7pyhQG4q+esgc67OHi4fjAZCu8lfxmIafiKdckvYOTXEzyyFOxMdfnsRZdUkXHP+Dh6Jb/xejg3tQVUXNvjyxOJmNLfU6zOXST7IvYOG/8KPNqqT1JQg6W3qhoYlA99t6+HFjhPXcwRBmFLTQV6WfmTMdeQz1P0G8J+Tp+31kUZlkZkUmmkJZJ7GFT9pVgY=
